/**
 * Created by uroszivaljevic on 10/2/17.
 */

export const DogsActions = {
    GET_DOGS_STARTED: "GET_DOGS_STARTED",
    GET_DOGS_SUCCESS: "GET_DOGS_SUCCESS",
    GET_DOGS_FAILED: "GET_DOGS_FAILED",
    ADD_DOG_STARTED: "ADD_DOG_STARTED",
    ADD_DOG_SUCCESS: "ADD_DOG_SUCCESS",
    ADD_DOG_FAILED: "ADD_DOG_FAILED",
};

export const LeaguesActions = {
    GET_LEAGUES_STARTED: "GET_LEAGUES_STARTED",
    GET_LEAGUES_SUCCESS: "GET_LEAGUES_SUCCESS",
    GET_LEAGUES_FAILED: "GET_LEAGUES_FAILED",
};

export const ContestsActions = {
    GET_CONTESTS_STARTED: "GET_CONTESTS_STARTED",
    GET_CONTESTS_SUCCESS: "GET_CONTESTS_SUCCESS",
    GET_CONTESTS_FAILED: "GET_CONTESTS_FAILED",
    ADD_CONTEST_STARTED: "ADD_CONTEST_STARTED",
    ADD_CONTEST_SUCCESS: "ADD_CONTEST_SUCCESS",
    ADD_CONTEST_FAILED: "ADD_CONTEST_FAILED",
    GET_CONTEST_STARTED: "GET_CONTEST_STARTED",
    GET_CONTEST_SUCCESS: "GET_CONTEST_SUCCESS",
    GET_CONTEST_FAILED: "GET_CONTEST_FAILED",
};

export const TasksActions = {
    GET_TASKS_STARTED: "GET_TASKS_STARTED",
    GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
    GET_TASKS_FAILED: "GET_TASKS_FAILED",
    POST_DOG_TASKS_STARTED: "POST_DOG_TASKS_STARTED",
    POST_DOG_TASKS_SUCCESS: "POST_DOG_TASKS_SUCCESS",
    POST_DOG_TASKS_FAILED: "POST_DOG_TASKS_FAILED",
}