/**
 * Created by uroszivaljevic on 10/2/17.
 */

export const DogsActions = {
    GET_DOGS_STARTED: "GET_DOGS_STARTED",
    GET_DOGS_SUCCESS: "GET_DOGS_SUCCESS",
    GET_DOGS_FAILED: "GET_DOGS_FAILED",
    ADD_DOG_STARTED: "ADD_DOG_STARTED",
    ADD_DOG_SUCCESS: "ADD_DOG_SUCCESS",
    ADD_DOG_FAILED: "ADD_DOG_FAILED",
};

export const LeaguesActions = {
    GET_LEAGUES_STARTED: "GET_LEAGUES_STARTED",
    GET_LEAGUES_SUCCESS: "GET_LEAGUES_SUCCESS",
    GET_LEAGUES_FAILED: "GET_LEAGUES_FAILED",
};